### ISSUE TITLE
move all data to the Maven Wave GCS Buckets

### ISSUE THREAD

**Issue by brianray** [data-describe/awesome-data-science-models#21]
All the data should be pulling from the MW Public GCP Buckets: 

- https://storage.googleapis.com/amazing-public-data/black_friday/test.csv
- https://storage.googleapis.com/amazing-public-data/lending_club/lending_club_data.tsv
- ...

But the example don't seem to pull from these.

Note for MW folks: this is https://console.cloud.google.com/storage/browser/amazing-public-data;tab=objects?forceOnBucketsSortingFiltering=false&project=data-describe&prefix=&forceOnObjectsSortingFiltering=false

For example:

- [ ] Census-income ttps://archive.ics.uci.edu/ml/machine-learning-databases/adult/adult.data and *.text
- [ ] for black-friday https://github.com/data-describe/awesome-data-science-models/tree/master/black-friday/EDA/Data
- [ ] on cellular image bipin_workshop_bucket is used should ber the public bucket
- [ ] Chicago taxi looks fine as it uses a pubic GCP data set but we need to give instructions on how to authenticate their own GCP project for access
- [ ] lending club should be moved from gs://amazing-public-data/lending_club/lending_club_data.tsv
- [ ] pitch predictor uses a Collect-Games method https://github.com/data-describe/awesome-data-science-models/blob/master/pitch-predictor/answers/components/collectStats/ParDoFns/collectGames.py#L13, should probably freeze that data and put it in our public bucket

**Comment by brianray** [comment]
One last thing, for the Census-income can you add more meaningful headers and make sure that the change does not break the example here

**Comment by dandawg** [comment]
Definitely. I'll get working on it.

**Comment by dandawg** [comment]
I added columns to the train and test data for census income with the following commands.
```
echo "age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income" > census_income_data_adult.data; cat census_income_data_adult.data.old >> census_income_data_adult.data

echo "age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,income" > census_income_data_adult.test; cat census_income_data_adult.test.old >> census_income_data_adult.test
```
The columns were retrieved from the original source, and after I made the change above, I validated that these columns were correct (they matched the data), and that they can be imported seamlessly with pandas.read_csv.

As a side note, there are a few quirks with the data that I did not address, because they are part of what makes the dataset interesting during EDA. These quirks do not interfere with the initial data read in.

In addition, the source data includes a file called `adult.names`. The file includes context on the dataset (i.e. possible column values) and past modeling results. I have added this to the census_income folder under the name `census_income_data_adult.names`, as it looks to be helpful. We can take it off again if there is a reason not to include it there.

**Comment by brianray** [comment]
do the demos still work?

**Comment by dandawg** [comment]
I'll make sure they do for the census_income dataset, and make any changes if necessary.

**Comment by dandawg** [comment]
I have one more notebook to fix. The What if notebook pulls directly from the source code and renames the columns. It was also saved in a state of not having been run (no outputs), and I'll need to figure out if this is best going forward.

**Comment by brianray** [comment]
any updates on this

**Comment by brianray** [comment]
should it be closed

**Comment by dandawg** [comment]
I have one notebook to tie up. I'm working on it now, and should be done very soon.
